Data sorting.
JuliaKholodetska/Task2-Full-Stack-JS-Internship pull request #2
Opened 2021-03-17 14:56 UTC by JuliaKholodetska

- sorting done on BE;
- use bubble sort;
- sorting direction icon appear next to a column name;
- sorting done for string and number fields.

2021-03-17 17:48 UTC, MariiaKolisnyk requested changes

2021-03-17 19:20 UTC, JuliaKholodetska commented on client/app.js
> +    function clearClass() {
this function is not in updateTable

2021-03-18 09:13 UTC, MariiaKolisnyk commented on client/app.js
> +    function clearClass() {
my apologies, I might have taken it wrong.

2021-03-18 11:33 UTC, MariiaKolisnyk approved these changes

2021-03-18 11:40 UTC, merged